<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_31</name>
   <tag></tag>
   <elementGuidId>fd62e6cb-a3e9-4b20-a186-913698dd9385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[47]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb1bc347-0520-4d51-80e6-7bf0d03c3212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e132586f-4629-4680-ab88-d81785b80ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>31, Monday, March 2025. Available. Select as check-in date.</value>
      <webElementGuid>e1921891-56e1-49c1-a30d-bb1d99385dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d11exu1w atm_vy_1osqo2v atm_1w_gbua2q atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_fb_1cl4t0h atm_c8_dlk8xv atm_cs_10d11i2 atm_7l_dezgoh atm_9j_tlke0l atm_vb_glywfm atm_70_glywfm atm_2d_n7od8j atm_3f_n7od8j atm_lb_n7od8j atm_lh_n7od8j atm_vy_1osqo2v_vmtskl atm_e2_1osqo2v_vmtskl atm_mk_stnw88_vmtskl atm_92_1yyfdc7_vmtskl atm_5j_1ssbidh_vmtskl atm_wq_1mrwo0b_vmtskl atm_3f_11x2w5_1rqz0hn_uv4tnr atm_kd_glywfm_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_aaiy6o_9xuho3 atm_70_1kppo7g_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_aaiy6o_1buez3b_1oszvuo atm_70_1kppo7g_1buez3b_1oszvuo atm_uc_glywfm_1buez3b_1o31aam d1h3s0zq atm_mj_1wugsn5 dir dir-ltr</value>
      <webElementGuid>06497f68-28ac-446d-8bf9-135f74515915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state--date-string</name>
      <type>Main</type>
      <value>2025-03-31</value>
      <webElementGuid>ef716b08-4628-4b29-89f9-4812a3b05f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0309a680-747e-4077-8152-30d4ed7dcdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>644f56f3-44ee-48e2-a702-61e8b30f2c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel--tabs--0&quot;)/div[@class=&quot;d1xjigzy atm_h_1h6ojuz__7pk1ck atm_9s_1txwivl__7pk1ck atm_ar_1bp4okc__7pk1ck atm_fc_1h6ojuz__7pk1ck dir dir-ltr&quot;]/div[@class=&quot;h1yby4o2 atm_9s_1o8liyq atm_mk_h2mmj6 h12enwjs atm_vy_1a0j60c atm_gz_vgba9w atm_h0_vgba9w dir dir-ltr&quot;]/div[4]/div[@class=&quot;e46z8ty atm_l0_15vqwwr atm_vy_1osqo2v dir dir-ltr&quot;]/div[@class=&quot;ecjc60a atm_9s_1txwivl atm_uq_1e032xh atm_uv_1ytfnp0 atm_h_v2br90 dir dir-ltr&quot;]/div[@class=&quot;m1uqgy7e atm_9s_11p5wf0 atm_dz_1u8mbql atm_n5_yh40bf atm_vy_1osqo2v atm_l8_1w78mzc atm_ks_zryt35 h1pfdthe atm_gz_d4y9na atm_h0_d4y9na dir dir-ltr&quot;]/button[@class=&quot;d11exu1w atm_vy_1osqo2v atm_1w_gbua2q atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_fb_1cl4t0h atm_c8_dlk8xv atm_cs_10d11i2 atm_7l_dezgoh atm_9j_tlke0l atm_vb_glywfm atm_70_glywfm atm_2d_n7od8j atm_3f_n7od8j atm_lb_n7od8j atm_lh_n7od8j atm_vy_1osqo2v_vmtskl atm_e2_1osqo2v_vmtskl atm_mk_stnw88_vmtskl atm_92_1yyfdc7_vmtskl atm_5j_1ssbidh_vmtskl atm_wq_1mrwo0b_vmtskl atm_3f_11x2w5_1rqz0hn_uv4tnr atm_kd_glywfm_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_aaiy6o_9xuho3 atm_70_1kppo7g_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_aaiy6o_1buez3b_1oszvuo atm_70_1kppo7g_1buez3b_1oszvuo atm_uc_glywfm_1buez3b_1o31aam d1h3s0zq atm_mj_1wugsn5 dir dir-ltr&quot;]</value>
      <webElementGuid>dde34463-5b68-431f-bd2f-ba3c12178e74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[47]</value>
      <webElementGuid>0e755b3f-a90d-48c2-82db-e5f4b4eeeb0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel--tabs--0']/div/div/div[4]/div/div/div/button[37]</value>
      <webElementGuid>c557084d-75de-4702-9ef3-9f5c171eb897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[2]/following::button[37]</value>
      <webElementGuid>812bbccb-af05-4358-9363-496df9ac5511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[2]/following::button[37]</value>
      <webElementGuid>6e9b3c11-bfd0-4f99-b6b5-2e566251aceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exact dates'])[1]/preceding::button[41]</value>
      <webElementGuid>5944dfdd-88be-439d-acda-29c0d123b993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='±1 day'])[1]/preceding::button[41]</value>
      <webElementGuid>53347394-c327-4585-ab83-24f7d321eee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>6aec9ed9-0621-4232-ba0b-e73878cff88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[37]</value>
      <webElementGuid>2b63ab4e-afce-4d97-83f4-e920bebb553e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '31' or . = '31')]</value>
      <webElementGuid>94bde9ef-9f8f-4bf1-8381-c18aa893914f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
