<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_31, Monday, March 2025. Available. Select</name>
   <tag></tag>
   <elementGuidId>c27468ae-dccc-40f6-8b5c-9584451e16c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = '31, Monday, March 2025. Available. Select as check-in date.']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;\33 1\,\ Monday\,\ March\ 2025\.\ Available\.\ Select\ as\ check-in\ date\.&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bcfe9262-54ab-495f-b47f-0876b9da53fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f5deca9-0804-4c51-acf1-037ae030b27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>31, Monday, March 2025. Available. Select as check-in date.</value>
      <webElementGuid>8a697054-7bd2-4b3b-bf72-51d5cd0b23b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d11exu1w atm_vy_1osqo2v atm_1w_gbua2q atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_fb_1cl4t0h atm_c8_dlk8xv atm_cs_10d11i2 atm_7l_dezgoh atm_9j_tlke0l atm_vb_glywfm atm_70_glywfm atm_2d_n7od8j atm_3f_n7od8j atm_lb_n7od8j atm_lh_n7od8j atm_vy_1osqo2v_vmtskl atm_e2_1osqo2v_vmtskl atm_mk_stnw88_vmtskl atm_92_1yyfdc7_vmtskl atm_5j_1ssbidh_vmtskl atm_wq_1mrwo0b_vmtskl atm_3f_11x2w5_1rqz0hn_uv4tnr atm_kd_glywfm_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_aaiy6o_9xuho3 atm_70_1kppo7g_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_aaiy6o_1buez3b_1oszvuo atm_70_1kppo7g_1buez3b_1oszvuo atm_uc_glywfm_1buez3b_1o31aam d1h3s0zq atm_mj_1wugsn5 dir dir-ltr</value>
      <webElementGuid>43d9678f-f994-46f1-a64f-39240b928ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state--date-string</name>
      <type>Main</type>
      <value>2025-03-31</value>
      <webElementGuid>d525c35d-d977-4091-8ffc-a7013dcaceed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7209b1bb-806e-44ac-ad93-08b78f04b5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31, Monday, March 2025. Available. Select</value>
      <webElementGuid>94cfb031-85ba-4daa-b891-8b40322dec94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>5edd2554-e832-43a5-a56e-dca6a3e928fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c31e51d396d4179fe5fc6dc0f7fed963</value>
      <webElementGuid>d90a3f99-ca92-4338-9e2c-911d5de3ef86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = '31, Monday, March 2025. Available. Select as check-in date.']</value>
      <webElementGuid>6d31bb8a-cff3-4365-8e6d-39b1430078f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = '31, Monday, March 2025. Available. Select as check-in date.']</value>
      <webElementGuid>148caf67-9c3b-45a6-a545-1f0cc9953224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '31, Monday, March 2025. Available. Select' or . = '31, Monday, March 2025. Available. Select')]</value>
      <webElementGuid>06d276a1-41a2-42d1-8d58-aaad00a6c44b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
