<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_31_1</name>
   <tag></tag>
   <elementGuidId>d95be32d-97d4-48c4-ab1d-872cb0c8a7e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[49]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.d11exu1w.atm_vy_1osqo2v.atm_1w_gbua2q.atm_mk_h2mmj6.atm_9s_1txwivl.atm_h_1h6ojuz.atm_fc_1h6ojuz.atm_fb_1cl4t0h.atm_c8_dlk8xv.atm_cs_10d11i2.atm_9j_tlke0l.atm_vb_glywfm.atm_70_glywfm.atm_2d_n7od8j.atm_3f_n7od8j.atm_lb_n7od8j.atm_lh_n7od8j.atm_vy_1osqo2v_vmtskl.atm_e2_1osqo2v_vmtskl.atm_mk_stnw88_vmtskl.atm_92_1yyfdc7_vmtskl.atm_5j_1ssbidh_vmtskl.atm_wq_1mrwo0b_vmtskl.atm_kd_glywfm_1w3cfyq.atm_3f_glywfm_e4a3ld.atm_l8_idpfg4_e4a3ld.atm_gi_idpfg4_e4a3ld.atm_3f_glywfm_1r4qscq.atm_kd_glywfm_6y7yyg.atm_uc_aaiy6o_9xuho3.atm_70_1kppo7g_9xuho3.atm_uc_glywfm_9xuho3_1rrf6b5.atm_kd_glywfm_pfnrn2_1oszvuo.atm_3f_glywfm_1icshfk_1oszvuo.atm_l8_idpfg4_1icshfk_1oszvuo.atm_gi_idpfg4_1icshfk_1oszvuo.atm_3f_glywfm_b5gff8_1oszvuo.atm_kd_glywfm_2by9w9_1oszvuo.atm_uc_aaiy6o_1buez3b_1oszvuo.atm_70_1kppo7g_1buez3b_1oszvuo.atm_uc_glywfm_1buez3b_1o31aam.d1h3s0zq.atm_mj_1wugsn5.i1jjp0hq.atm_7l_1p8m8iw.atm_2d_dezgoh_vmtskl.atm_3f_1tfe5xk_1rqz0hn.undefined.dir.dir-ltr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c63b46c-9014-4304-be61-2ea8dc24c453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42cc1cb8-1b44-49e2-9ef0-d9578bb5dc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>31, Monday, March 2025. Selected check-in date.</value>
      <webElementGuid>8d7d3920-3ea9-424e-b7ed-83e75e76bdeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d11exu1w atm_vy_1osqo2v atm_1w_gbua2q atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_fb_1cl4t0h atm_c8_dlk8xv atm_cs_10d11i2 atm_9j_tlke0l atm_vb_glywfm atm_70_glywfm atm_2d_n7od8j atm_3f_n7od8j atm_lb_n7od8j atm_lh_n7od8j atm_vy_1osqo2v_vmtskl atm_e2_1osqo2v_vmtskl atm_mk_stnw88_vmtskl atm_92_1yyfdc7_vmtskl atm_5j_1ssbidh_vmtskl atm_wq_1mrwo0b_vmtskl atm_kd_glywfm_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_aaiy6o_9xuho3 atm_70_1kppo7g_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_aaiy6o_1buez3b_1oszvuo atm_70_1kppo7g_1buez3b_1oszvuo atm_uc_glywfm_1buez3b_1o31aam d1h3s0zq atm_mj_1wugsn5 i1jjp0hq atm_7l_1p8m8iw atm_2d_dezgoh_vmtskl atm_3f_1tfe5xk_1rqz0hn undefined dir dir-ltr</value>
      <webElementGuid>821a6cc4-1110-4b12-9248-6a911f11d902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state--date-string</name>
      <type>Main</type>
      <value>2025-03-31</value>
      <webElementGuid>94dfd728-6443-43f9-aa99-a91b42f46085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a259ef4-b569-413d-9c27-5138ece06308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>555ad502-f719-4881-9db0-07f0143b423b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel--tabs--0&quot;)/div[@class=&quot;d1xjigzy atm_h_1h6ojuz__7pk1ck atm_9s_1txwivl__7pk1ck atm_ar_1bp4okc__7pk1ck atm_fc_1h6ojuz__7pk1ck dir dir-ltr&quot;]/div[@class=&quot;h1yby4o2 atm_9s_1o8liyq atm_mk_h2mmj6 h12enwjs atm_vy_1a0j60c atm_gz_vgba9w atm_h0_vgba9w dir dir-ltr&quot;]/div[4]/div[@class=&quot;e46z8ty atm_l0_15vqwwr atm_vy_1osqo2v dir dir-ltr&quot;]/div[@class=&quot;ecjc60a atm_9s_1txwivl atm_uq_1e032xh atm_uv_1ytfnp0 atm_h_v2br90 dir dir-ltr&quot;]/div[@class=&quot;m1uqgy7e atm_9s_11p5wf0 atm_dz_1u8mbql atm_n5_yh40bf atm_vy_1osqo2v atm_l8_1w78mzc atm_ks_zryt35 h1pfdthe atm_gz_d4y9na atm_h0_d4y9na dir dir-ltr&quot;]/button[@class=&quot;d11exu1w atm_vy_1osqo2v atm_1w_gbua2q atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_fb_1cl4t0h atm_c8_dlk8xv atm_cs_10d11i2 atm_9j_tlke0l atm_vb_glywfm atm_70_glywfm atm_2d_n7od8j atm_3f_n7od8j atm_lb_n7od8j atm_lh_n7od8j atm_vy_1osqo2v_vmtskl atm_e2_1osqo2v_vmtskl atm_mk_stnw88_vmtskl atm_92_1yyfdc7_vmtskl atm_5j_1ssbidh_vmtskl atm_wq_1mrwo0b_vmtskl atm_kd_glywfm_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_aaiy6o_9xuho3 atm_70_1kppo7g_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_aaiy6o_1buez3b_1oszvuo atm_70_1kppo7g_1buez3b_1oszvuo atm_uc_glywfm_1buez3b_1o31aam d1h3s0zq atm_mj_1wugsn5 i1jjp0hq atm_7l_1p8m8iw atm_2d_dezgoh_vmtskl atm_3f_1tfe5xk_1rqz0hn undefined dir dir-ltr&quot;]</value>
      <webElementGuid>196dcf78-413b-422b-9e90-d37d7977257d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[49]</value>
      <webElementGuid>4916a729-8ee4-4579-8d28-7703d6e2ffca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel--tabs--0']/div/div/div[4]/div/div/div/button[37]</value>
      <webElementGuid>0d02d2f6-606b-4a2d-aa2a-779091f3a39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[2]/following::button[37]</value>
      <webElementGuid>8d33c56d-53e9-47c7-98d5-57da6958476a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[2]/following::button[37]</value>
      <webElementGuid>6b0b23ca-2057-46e9-977f-b8015f042fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exact dates'])[1]/preceding::button[41]</value>
      <webElementGuid>f757848c-f592-4f4c-80ef-055620d2b8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='±1 day'])[1]/preceding::button[41]</value>
      <webElementGuid>10b4fdbb-9fbd-420f-996d-d28eb127a171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>a4c3c8a8-aebb-4cf1-9d41-b57c7ba15403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[37]</value>
      <webElementGuid>921f3b86-0b68-45fe-878e-efc50d6ef3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '31' or . = '31')]</value>
      <webElementGuid>9cb3c0e7-d309-40b5-8abf-11cfe65f719d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
