<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_bigsearch-query-location-suggestion-0</name>
   <tag></tag>
   <elementGuidId>d02c4837-5a5c-4f12-8a9c-7d0692053864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;option-0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8a52e8e8-ee3b-4af3-bc37-b4a6f6836d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d81c23c0-c0c0-4d22-8c06-fabc9bcbd320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>42a13ec7-6301-48d2-818d-4a05cf7539ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigsearch-query-location-suggestion-0</value>
      <webElementGuid>0055e37e-0635-4d90-aeb6-8fd7f2081d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>be7d66cc-cb15-4378-a538-1511c1856577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>option-0</value>
      <webElementGuid>bad36a65-c07b-48d2-8822-b1027f469b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prefix</name>
      <type>Main</type>
      <value>SYSTEM_LOCATION_STROKED</value>
      <webElementGuid>cbb21ce6-06cb-4513-b54a-d8266966570b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c569q9j atm_r2_1j28jx2 atm_26_1qwqy05 atm_5j_kitwna atm_9j_tlke0l atm_9s_1txwivl atm_cx_exct8b atm_gw_1rrn7iu atm_l8_ftgil2 atm_kd_glywfm_1w3cfyq atm_uc_aaiy6o_1w3cfyq atm_26_1qwqy05_1w3cfyq atm_70_6ezzhz_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_glywfm_1w3cfyq_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_uc_aaiy6o_pfnrn2_1oszvuo atm_26_1qwqy05_pfnrn2_1oszvuo atm_70_6ezzhz_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_glywfm_pfnrn2_1o31aam atm_26_jk66pa_1nos8r_uv4tnr atm_26_jk66pa_csw3t1 dir dir-ltr</value>
      <webElementGuid>44ab1e34-968e-48ce-a4f8-defe4059fb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bigsearch-query-location-suggestion-0</value>
      <webElementGuid>1b416402-2681-4179-936d-657227428a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Goa</value>
      <webElementGuid>48dc2b90-7b44-46b7-b9d2-a9f86dc66a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a164ace39ffc2db4d6fd347bc836c06a</value>
      <webElementGuid>1b563e10-0b00-4ec2-ac98-2ef757dd1331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'option-0']</value>
      <webElementGuid>2433a1fa-65e5-44e6-93db-e4bc79c391c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'option-0']</value>
      <webElementGuid>fd7e0917-0e00-4a3b-8782-36fa9521481a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'bigsearch-query-location-suggestion-0' and (text() = 'bigsearch-query-location-suggestion-0' or . = 'bigsearch-query-location-suggestion-0')]</value>
      <webElementGuid>23113e3e-20bb-49c0-b3b2-f2393a1bcd4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
