<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Goa</name>
   <tag></tag>
   <elementGuidId>c753b95d-fe13-4453-ab30-bb69064972cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bigsearch-query-location-suggestion-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bigsearch-query-location-suggestion-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2384e8d-5084-46ea-a91f-679bb0d5054b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a57f10d2-bc4a-4a6b-bfe5-0acad271aa3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>041eab1e-915b-409c-a0b6-dfbab43c79d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigsearch-query-location-suggestion-0</value>
      <webElementGuid>5381e348-82a9-446e-adb3-5b091188c0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e867e18e-abd3-4d64-bdae-19226ce9bae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>option-0</value>
      <webElementGuid>a0e1cc5f-1c10-466d-99dd-2a755cf3059a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prefix</name>
      <type>Main</type>
      <value>SYSTEM_LOCATION_STROKED</value>
      <webElementGuid>5172753b-e419-4cf3-a5ae-918376159181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c569q9j atm_r2_1j28jx2 atm_5j_kitwna atm_9j_tlke0l atm_9s_1txwivl atm_cx_exct8b atm_gw_1rrn7iu atm_l8_ftgil2 atm_kd_glywfm_1w3cfyq atm_uc_aaiy6o_1w3cfyq atm_26_1qwqy05_1w3cfyq atm_70_6ezzhz_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_glywfm_1w3cfyq_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_uc_aaiy6o_pfnrn2_1oszvuo atm_26_1qwqy05_pfnrn2_1oszvuo atm_70_6ezzhz_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_glywfm_pfnrn2_1o31aam atm_26_jk66pa_1nos8r_uv4tnr atm_26_jk66pa_csw3t1 c16b4zta atm_26_jk66pa dir dir-ltr</value>
      <webElementGuid>71f058e9-9395-46d4-937e-94bccdd24a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Goa</value>
      <webElementGuid>ee1d4663-ac58-42a6-aa90-a4ee8b70e0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigsearch-query-location-suggestion-0&quot;)</value>
      <webElementGuid>74063e04-7e08-4d66-aa88-ad0a9f421880</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='bigsearch-query-location-suggestion-0']</value>
      <webElementGuid>4a8a8159-10bc-42b5-ab94-1b9dd206b3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigsearch-query-location-listbox']/div</value>
      <webElementGuid>5bc3cf55-59e0-4507-8e33-c195788dce3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where'])[1]/following::div[5]</value>
      <webElementGuid>af0253e8-9cc3-481e-b425-20000396ecb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experiences'])[1]/following::div[11]</value>
      <webElementGuid>8cbf0244-104a-402a-8958-5974c54fb14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='North Goa'])[1]/preceding::div[5]</value>
      <webElementGuid>b8d1ba48-9624-4570-a95d-adb504f9fba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>b40009c6-7a57-41f6-ac4e-b51bdcf93c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'bigsearch-query-location-suggestion-0' and (text() = 'Goa' or . = 'Goa')]</value>
      <webElementGuid>4cff0865-ce14-4fd5-872e-ab9d3fff7eff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
