<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_Skip to content_hdlenu1 atm_mk_1if85_4586a8</name>
   <tag></tag>
   <elementGuidId>a61f1bcc-fe39-4cc5-b6ad-4a22594ebdc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-application']/div/div/div/div/div[3]/header</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>header.hdlenu1.atm_mk_1if85x1.atm_tk_idpfg4.atm_vy_1osqo2v.atm_wq_zo7u8.atm_e2_1sbmx35.dir.dir-ltr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>256c1033-bb21-4a1f-9b70-ee92199b69b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hdlenu1 atm_mk_1if85x1 atm_tk_idpfg4 atm_vy_1osqo2v atm_wq_zo7u8 atm_e2_1sbmx35 dir dir-ltr</value>
      <webElementGuid>98fda264-72f6-4322-b6d5-0c755e126deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-application&quot;)/div[1]/div[@class=&quot;t1bgcr6e  cjz5kiq&quot;]/div[1]/div[1]/div[@class=&quot;c13hltkk atm_lcucu6_1ylpe5n atm_1298uvg_idpfg4 atm_mk_h2mmj6 atm_fb_1cl4t0h atm_lcucu6_1tcgj5g__1v156lz atm_1d0w6nq_mlf1tl__1v156lz atm_1d0w6nq_mlf1tl__qky54b atm_1d0w6nq_nc1ex2__1h2hqoz atm_1d0w6nq_795ys9__jx8car atm_1q65bst_nc1ex2__jx8car atm_1q65bst_1eblpci__w5e62l cslie43 atm_soqhx5_zdsjhe dir dir-ltr&quot;]/header[@class=&quot;hdlenu1 atm_mk_1if85x1 atm_tk_idpfg4 atm_vy_1osqo2v atm_wq_zo7u8 atm_e2_1sbmx35 dir dir-ltr&quot;]</value>
      <webElementGuid>88edcb08-e3c6-440a-af9f-e093c1803536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-application']/div/div/div/div/div[3]/header</value>
      <webElementGuid>8390616e-9bbd-41b4-885d-f1a184d1bc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to content'])[1]/following::header[1]</value>
      <webElementGuid>ec9635dc-e1e6-4057-a643-25d0478c5218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show map'])[1]/preceding::header[1]</value>
      <webElementGuid>47ffd6fc-304b-4a96-b5b0-5c63efe4e7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>93dcfb16-0931-42a2-9db6-58183b4df168</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
