<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_orangehrm-login-branding</name>
   <tag></tag>
   <elementGuidId>f190dd9c-95d9-4073-8adc-fdcb32fc2810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.orangehrm-login-branding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-login-branding ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ea93f7ac-cd9d-449e-b8f1-65fe83f33725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-login-branding</value>
      <webElementGuid>1f8cb990-95cb-4ece-99c8-941ebbfa7bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>orangehrm-login-branding</value>
      <webElementGuid>fab7ddf8-e985-4e5d-9e6b-91fdf563a306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5ec5a9699ebdab1d0ebbad6f79d8ed26</value>
      <webElementGuid>925aa7c5-cdf7-437f-87eb-ebd2a2a778c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-login-branding ')]</value>
      <webElementGuid>aef1765a-39f2-4648-bdd5-a6d9ae1e1b83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-login-branding ')]</value>
      <webElementGuid>a8950572-5c6d-48d8-9005-3ace539a2a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'orangehrm-login-branding' or . = 'orangehrm-login-branding')]</value>
      <webElementGuid>2cc69f52-4e99-4bbe-829d-af197f604db5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
