<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_About</name>
   <tag></tag>
   <elementGuidId>7c63c747-fa84-4b95-b4b1-e49173d415a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.orangehrm-main-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-main-title ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>f67e76eb-6383-498c-8c33-eaacb8d7d5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-text oxd-text--h6 orangehrm-main-title</value>
      <webElementGuid>6e35acf0-606f-4a22-9088-8bc150027e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About</value>
      <webElementGuid>674a124f-d0fd-4046-859b-26bd47e37033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>About</value>
      <webElementGuid>7b23ee4a-dc80-41d9-91c7-e98dd222a899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5b58d0639079eb67ea0a830bcf6582ac</value>
      <webElementGuid>488f1704-4164-4b1d-8c7b-952e4032e557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-main-title ')]</value>
      <webElementGuid>0319809d-d5bd-4199-95c3-4a688753431f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' orangehrm-main-title ')]</value>
      <webElementGuid>b60a4962-8071-4bed-a0bd-a182b7471059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'About' or . = 'About')]</value>
      <webElementGuid>8b82d2c1-c352-4d6b-8e4e-2d877e78374c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
